# @see https://github.com/Sylius/SyliusResourceBundle/blob/master/docs/index.md
sylius_resource:
    # Override default settings
    #settings:

    # Configure your resources
    resources:
        app.form:
            driver: doctrine/orm
            classes:
                model: App\Entity\Form
                controller: App\Controller\FormBuilderController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository
        app.form_element:
            driver: doctrine/orm
            classes:
                model: App\Entity\FormElement
                controller: App\Controller\FormElementController
                repository: Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository